solve-a:	
	python a.py < A > a.out
	Del "A"
solve-b:
	python b.py < B > b.out
	Del "B"
solve-c:
	python c.py < C > c.out
	Del "C"
solve-d:
	python d.py < D > d.out
	Del "D"
solve-e:
	python e.py < E > e.out
	Del "E"
solve-f:
	python f.py < F > f.out
	Del "F"
solve-g:
	python g.py < G > g.out
	Del "G"
solve-h:
	python h.py < H > h.out
	Del "H"
solve-i:
	python i.py < I > i.out
	Del "I"
solve-j:
	python j.py < J > j.out
	Del "J"
solve-k:
	python k.py < K > k.out
	Del "k"