solve-a:	
	python a.py < A > a.out
	
solve-b:
	python b.py < B > b.out
	
solve-c:
	python c.py < C > c.out
	
solve-d:
	python d.py < D > d.out
	
solve-e:
	python e.py < E > e.out
	
solve-f:
	python f.py < F > f.out
	
solve-g:
	python g.py < G > g.out
	
solve-h:
	python h.py < H > h.out
	
solve-i:
	python i.py < I > i.out
	
solve-j:
	python j.py < J > j.out
	
solve-k:
	python k.py < K > k.out
	