solve-a:
	python a.py < in\A > out\a.out
	Del "in\A"
solve-b:
	python b.py < in\B > out\b.out
	Del "in\B"
solve-c:
	python c.py < in\C > out\c.out
	Del "in\C"
solve-d:
	python d.py < in\D > out\d.out
	Del "in\D"
solve-e:
	python e.py < in\E > out\e.out
	Del "in\E"
solve-f:
	python f.py < in\F > out\f.out
	Del "in\F"
solve-g:
	python g.py < in\G > out\g.out
	Del "in\G"
solve-h:
	python h.py < in\H > out\h.out
	Del "in\H"
solve-i:
	python i.py < in\I > out\i.out
	Del "in\I"
solve-j:
	python j.py < in\J > out\j.out
	Del "in\J"
solve-k:
	python k.py < in\K > out\k.out
	Del "in\k"